name: flutter_apns_x
description: Demonstrates how to use the flutter_apnsX plugin.
version: 0.0.1
homepage: https://github.com/Money1998/custom_apnsX.git

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.12
  firebase_core: ^2.6.0
  firebase_messaging:
    git:
      url: https://github.com/bryantwilliam/flutterfire.git
      path: packages/firebase_messaging/firebase_messaging
      ref: v14.2.2


#  flutter_local_notifications:
#    git:
#      url: https://github.com/MaikuB/flutter_local_notifications/tree/master/flutter_local_notifications

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides: